export const subreddits = [
  "r/TodayILearned",
  "r/AskReddit",
  "r/explainlikeimfive",
  "r/UpliftingNews",
  "r/technews",
  "r/savedyouaclick",
  "r/olympics",
  "r/offbeat",
  "r/gamernews",
  "r/TechNewsToday",
  "r/nottheonion",
  "r/news",
  "r/worldnews",
  // top 120 tech
  "r/Futurology",
  "r/gadgets",
  "r/technology",
  "r/windows",
  "r/buildapc",
  "r/apple",
  "r/MechanicalKeyboards",
  "r/Xiaomi",
  "r/Amd",
  "r/technews",
  "r/hardware",
  "r/Windows10",
  "r/DataHoader",
  "r/oculus",
  "r/buildapcsales",
  "r/MouseReview",
  "r/tmobile",
  "r/HeadphoneAdvice",
  "r/linuxmasterrace",
  "r/programming",
  "r/ipad",
  "r/iiiiiiitttttttttttt",
  "r/cordcutters",
  "r/Surface",
  "r/hometheater",
  "r/headphones",
  "r/laptops",
  "r/techsupportmacgyver",
  "r/thinkpad",
  "r/AndroidQUestions",
  "r/Dell",
  "r/PhonesAreBad",
  "r/raspberry_pi",
  "r/rust",
  "r/reactjs",
  "r/homeassistant",
  "r/ATT",
  "r/hacking",
  "r/coding",
  "r/Sprint",
  "r/GalaxyS8",
  "r/GooglePixel",
  "r/retrobattlestations",
  "r/csharp",
  "r/oneplus",
  "r/verizon",
  "r/virtualreality",
  "r/engineering",
  "r/appleswap",
  "r/applehelp",
  "r/homelabsales",
  "r/jailbreak",
  "r/computing",
  "r/google",
  "r/GalaxyS9",
  "r/archlinux",
  "r/HomeNetworking",
  "r/ManufacturingPorn",
  "r/MatebookXPro",
  "r/webdev",
  "r/javascript",
  "r/androidthemes",
  "r/AVexchange",
  "r/software",
  "r/mechmarket",
  "r/GalaxyNote9",
  "r/AskNetsec",
  "r/Huawei",
  "r/chromeos",
  "r/WindowsMR",
  "r/gamedev",
  "r/Vive",
  "r/redditdev",
  "r/iOSthemes",
  "r/Alienware",
  "r/overclocking",
  "r/MachineLearning",
  "r/IPTV",
  "r/androidapps",
  "r/golang",
  
  // limited to 100 per dropdown



  // "r/msp",
  // "r/hardwareswap",
  // "r/macbookpro",
  // "r/computers",
  // "r/AskElectronices",
  // "r/abelton",
  // "r/IndianGaming",
  // "r/iOSProgramming",
  // "r/synology",
  // "r/AyyMD",
  // "r/iphone",
  // "r/androiddev",
  // "r/PowerShell",
  // "r/airpods",
  // "r/Machinists",
  // "r/googlehome",
  // "r/learnprogramming",
  // "r/linux",
  // "r/mac",
  // "r/techsupport",
  // "r/hackintosh",
  // "r/aws",
  // "r/arduino",
  // "r/homelab",
  // "r/learnpython",
  // "r/Python",
  // "r/AppleWatch",
  // "r/nvidia",
  // "r/Simulated",
  // "r/sysadmin",
  // "r/tech",
  // "r/samsung",
  // "r/Android",
  // "r/TechNewsToday",
  // "r/ProgrammerHumor",
  // "r/battlestations",
  // "r/cscareerquestions",
  // "r/discordapp"
]